In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])

print(a)

[1 2 3]


In [6]:
b = np.array([[9.0,8.0,7.0],[6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
a.ndim

1

In [8]:
a.shape

(3,)

In [9]:
b.shape

(2, 3)

In [10]:
a.dtype

dtype('int64')

In [24]:
a = np.array([1,2,3], dtype = 'int64')

print(a)

[1 2 3]


In [12]:
a.dtype

dtype('int16')

In [16]:
a.itemsize

4

In [18]:
a.size * a.itemsize

12

In [19]:
a.nbytes

12

In [33]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [28]:
a.shape

(3,)

In [35]:
a[ 1, 5]

13

In [36]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [38]:
a[:, 2]

array([ 3, 10])

In [39]:
a[0, 1:6:2]

array([2, 4, 6])

In [43]:
a[1,5] = 20
print(a)

a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [42]:
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [44]:
a[1,5] = 20
print(a)

a[:, 2] = [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [46]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [47]:
b[0,1,1]

4

In [48]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [49]:
b[:, 1 , :] = [[9,9],[8,8]]

In [50]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [51]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [53]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [55]:
np.ones((4,2,2), dtype ='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [56]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [57]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [58]:
np.random.rand(4,2)

array([[0.48817165, 0.21663516],
       [0.01822299, 0.12191428],
       [0.33418332, 0.13501794],
       [0.92110636, 0.35093674]])

In [59]:
np.random.random_sample(a.shape)

array([[0.26116421, 0.07628856, 0.23405015, 0.81059627, 0.71722586,
        0.61982627, 0.12230461],
       [0.83038012, 0.5981917 , 0.96581117, 0.70898144, 0.65587874,
        0.8037923 , 0.0546842 ]])

In [60]:
np.random.randint(7, size = (3,3) )

array([[0, 4, 3],
       [5, 3, 3],
       [1, 0, 3]])

In [61]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [64]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [66]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9

print(z)

output[1:4, 1:4] = z

print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [67]:
a = np.array([1,2,3])

b = a

b[0]= 100

print(a)

[100   2   3]


In [68]:
a = np.array([1,2,3])

b = a.copy()

b[0]= 100

print(a)

[1 2 3]


In [69]:
a = np.array([1,2,3,4])

print(a)

[1 2 3 4]


In [70]:
a + 2

array([3, 4, 5, 6])

In [71]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [72]:
b = np.array([1,0,1,0])

a + b

array([2, 2, 4, 4])

In [73]:
a ** 2

array([ 1,  4,  9, 16])

In [74]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [75]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [77]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [78]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [79]:
stats = np.array([[1,2,3],[4,5,6]])

stats

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
np.min(stats)

1

In [81]:
np.max(stats, axis = 1)

array([3, 6])

In [82]:
np.sum(stats)

21

In [83]:
np.sum(stats, axis = 0)

array([5, 7, 9])

In [84]:
before = np.array([[1,2,3,4],[5,6,7,8]])

print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [85]:
before = np.array([[1,2,3,4],[5,6,7,8]])

print(before.shape)

(2, 4)


In [86]:
before = np.array([[1,2,3,4],[5,6,7,8]])

print(before)

after = before.reshape((8,1))

print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [87]:
before = np.array([[1,2,3,4],[5,6,7,8]])

print(before)

after = before.reshape((4,2))

print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [88]:
before = np.array([[1,2,3,4],[5,6,7,8]])

print(before)

after = before.reshape((2,2,2))

print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [89]:
v1  = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [90]:
v1  = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [92]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [94]:
a = np.array([1,2,3,4,5,6,7,8,9])

a[[1,2,8]]

array([2, 3, 9])